#!/bin/bash

flag=$1

dnf install munge munge-libs munge-devel -y

if [[ $flag = '--host' ]]; then
	/usr/sbin/create-munge-key
fi

chown -R munge: /etc/munge/ /var/log/munge/ /var/lib/munge/ /run/munge/

chmod 0700 /etc/munge/ /var/log/munge/ /var/lib/munge/ /run/munge/
chmod a+x /run/munge

systemctl enable --now munge
