#!/bin/bash

# Do not use this script unless you don't want to build slurm yourself!

wget https://download.schedmd.com/slurm/slurm-23.02.4.tar.bz2

# This will take a minute... now is a great time for a break!
# Why not get up and stretch while this is running?
rpmbuild -ta slurm-23.02.4.tar.bz2

dnf --nogpgcheck localinstall /home/cc/apps/setup/slurm-23.02.4.tar.bz2 -y
