#!/bin/bash

set -x 

setupdir=/home/cc/apps/setup

$setupdir/02-install-munge --host

cat $setupdir/03-etc-security-limits.conf | sudo tee /etc/security/limits.conf

# TODO: check if no key exists
cp /etc/munge/munge.key /home/cc/apps/munge.key

munge -n | unmunge

$setupdir/head-only/04-install-maria
# Use 'HeroCommDB' as the password!
cp $setupdir/head-only/05-etc-my.cnf.d-innodb.cnf /etc/my.cnf.d/innodb.cnf
$setupdir/head-only/06-restart-maria
$setupdir/07-slurm-deps
$setupdir/08-install-slurm
$setupdir/head-only/09-setup-db
cp $setupdir/head-only/10-etc-slurm-slurmdbd.conf /etc/slurm/slurmdbd.conf
$setupdir/head-only/11-enable-slurmdbd
cp $setupdir/12-etc-slurm-slurm.conf /etc/slurm/slurm.conf
$setupdir/head-only/13-spawn-slurmctld
